# -*- coding: utf-8 -*-
"""dl_knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jg3P5vgNS9xWwHPkT2N-3i6fzYvNTWzc
"""

import numpy as np
from sklearn.neighbors import KNeighborsClassifier

train1 = np.genfromtxt('train_representation.csv',delimiter=',')
train2 = np.genfromtxt('test_representation.csv',delimiter=',')
train3 = np.genfromtxt('val_representation.csv',delimiter=',')
test = np.genfromtxt('fake_representation.csv',delimiter=',')

label1 = train1[1:, -1].astype(int)
label2 = train2[1:, -1].astype(int)
label3 = train3[1:, -1].astype(int)
train1 = train1[1:, :-1]
train2 = train2[1:, :-1]
train3 = train3[1:, :-1]
test_features = test[1:]

train_features = np.append(train1, train2, axis=0)
train_features = np.append(train_features, train3, axis=0)
train_labels = np.append(label1, label2, axis=0)
train_labels = np.append(train_labels, label3, axis=0)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_features, train_labels)

predictions = knn.predict(test_features)

col_list = ['feature_'+str(i) for i in range(128)]
col_list = col_list+['target']
col_list = np.array(col_list)
col_list = col_list.reshape((1,col_list.shape[0]))

predictions = predictions.reshape((predictions.shape[0],1))

prediction_file = np.append(test_features, predictions, axis=1)
prediction_file = np.append(col_list, prediction_file, axis=0)
prediction_file = prediction_file.astype(str)

np.savetxt("fake_predictions.csv", prediction_file, delimiter=",", fmt="%s")

